import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import home from '../styles/home.module.css'

const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="banner"></div>

            <div className="container">
                <div className={home.boxTitle}>
                    <h2 className="text-center">O que nós fazemos</h2>
                    <h3 className="text-center">
                        A mais de um década atendendo nossa comunidade local e áreas vizinhas
                    </h3>
                </div>

                <div className="grid md:grid-cols-3 bg-yellow-500 items-center text-center mb-10">
                    <div className={`${home.grid} `}>
                        <h4>Manutenção Preventiva</h4>
                        <p>
                            A melhor maneira de minimizar as avarias <br />é fazer a manutenção de
                            rotina.
                        </p>
                    </div>
                    <div className={home.grid}>
                        <Image
                            src="/images/about1.jpg"
                            alt="Troca de óleo"
                            width={360}
                            height={360}
                            layout="responsive"
                        />
                    </div>
                    <div className={home.grid}>
                        <h4>Retífica & Mecânica</h4>
                        <p>Usinagem de peças, corrigindo o desgaste e irregularidades das peças.</p>
                    </div>
                    <div className={home.grid}>
                        <Image
                            src="/images/about2.jpg"
                            alt="Troca de óleo"
                            width={360}
                            height={360}
                            layout="responsive"
                        />
                    </div>
                    <div className={home.grid}>
                        <h4>
                            Reparo e Serviços
                            <br /> de Freios
                        </h4>
                        <p>
                            A manutenção dos freios é importante para ajudar e garantir sua
                            segurança
                        </p>
                    </div>
                    <div className={home.grid}>
                        <Image
                            src="/images/about3.jpg"
                            alt="Troca de óleo"
                            width={360}
                            height={360}
                            layout="responsive"
                        />
                    </div>
                </div>

                <div className="mb-10">
                    <div className={home.boxTitle}>
                        <h2 className="text-center">Garantia de Resultado</h2>
                        <h3 className="text-center">
                            Oferecemos serviço completo de reparo e manutenção de automóveis
                        </h3>
                    </div>

                    <div className="grid md:grid-cols-3  gap-5">
                        <div className={`${home.garantia}`}>
                            <div className="flex items-start">
                                <div className="mr-4">
                                    <Image
                                        src="/images/warranty1.png"
                                        alt="Todas as marcas de carros"
                                        width={42}
                                        height={42}
                                        className="inline-block"
                                    />
                                </div>

                                <h5>
                                    Todas as marcas
                                    <br /> de carros
                                </h5>
                            </div>
                            <p>
                                Fornecemos uma variedade de serviços de reparação e manutenção para
                                todas as marcas e modelos de automóveis, mesmo para os exóticos e
                                vintage.
                            </p>
                        </div>
                        <div className={`${home.garantia}`}>
                            <div className="flex items-start">
                                <div className="mr-4">
                                    <Image
                                        src="/images/warranty2.png"
                                        alt="Serviços de variedades"
                                        width={42}
                                        height={42}
                                        className="inline-block"
                                    />
                                </div>

                                <h5>Serviços de variedades</h5>
                            </div>
                            <p>
                                O principal princípio do nosso trabalho é oferecer uma ampla gama de
                                serviços de reparação automóvel de qualidade e fazemos isso desde o
                                nosso primeiro dia.
                            </p>
                        </div>

                        <div className={home.garantia}>
                            <div className="flex items-start">
                                <div className="mr-4">
                                    <Image
                                        src="/images/warranty3.png"
                                        alt="Suporte de qualidade"
                                        width={42}
                                        height={42}
                                        className="inline-block"
                                    />
                                </div>

                                <h5 className="inline-block">Suporte de qualidade</h5>
                            </div>
                            <p>
                                A União Retífica e Mecânica oferece programas de suporte de
                                qualidade para todos os veículos que permitem que eles permaneçam
                                sempre totalmente funcionais.
                            </p>
                        </div>
                    </div>
                </div>
            </div>

            <div className={home.boxService}>
                <div className="container">
                    <div className="grid md:grid-cols-3 gap-5">
                        <div className="div">
                            Lorem ipsum dolor sit amet consectetur, adipisicing elit. Amet modi
                            recusandae similique, saepe placeat doloribus accusantium quaerat, dolor
                            eius labore nemo nam perferendis sint incidunt aut laborum perspiciatis.
                            Reiciendis, accusantium.
                        </div>
                        <div className="div">
                            Lorem ipsum dolor sit amet consectetur, adipisicing elit. Amet modi
                            recusandae similique, saepe placeat doloribus accusantium quaerat, dolor
                            eius labore nemo nam perferendis sint incidunt aut laborum perspiciatis.
                            Reiciendis, accusantium.
                        </div>
                        <div className="div">
                            Lorem ipsum dolor sit amet consectetur, adipisicing elit. Amet modi
                            recusandae similique, saepe placeat doloribus accusantium quaerat, dolor
                            eius labore nemo nam perferendis sint incidunt aut laborum perspiciatis.
                            Reiciendis, accusantium.
                        </div>
                    </div>
                </div>
            </div>
        </div>
    )
}
export default Home
