import type { NextPage } from 'next'
import Head from 'next/head'
import { useEffect, useRef } from 'react'
import { Loader } from '@googlemaps/js-api-loader'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
    const googlemap = useRef(null)
    useEffect(() => {
        const loader = new Loader({
            apiKey: process.env.NEXT_PUBLIC_API_KEY,
            version: 'weekly',
        })
        let map
        loader.load().then(() => {
            const google = window.google
            map = new google.maps.Map(googlemap.current, {
                center: { lat: -34.397, lng: 150.644 },
                zoom: 8,
            })
        })
    })
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className="banner"></div>
            <div id="map" ref={googlemap} />
        </div>
    )
}

export default Home
